print("giorgi is 11 ears old")
print("hi i am giorgi")
print("my surname is koranashvili")
print("my sister name is mariami")
print("i love playing football")
print("my favorite subject is math")
print("my hobby is dancing")
print("my favorite book is Harry Potter")
print("my fovorite food is xinkali")
print("i go to school everyday")